version: "3"
services:
  customer_backend:
    build: "./restaurant_customers_backend"
    command: bundle exec rackup --host '0.0.0.0' -p 3000
    ports:
      - "3000:3000" 
    volumes:
      - .:/myapp

  customers:
    build: "./restaurant_customers"
    command:
      bundle exec rackup --host '0.0.0.0' -p 2000  
    ports:
      - "2000:2000"
    volumes:
      - .:/myapp   
    depends_on:
      - customer_backend

  staff_backend:
    build: "./restaurant_staff_backend"
    command: bundle exec rackup --host '0.0.0.0' -p 4000
    ports:
      - "4000:4000" 
    volumes:
      - .:/myapp 
  
  staff:
    build: "./restaurant_staff"
    command:
      bundle exec rackup --host '0.0.0.0' -p 5000
    ports:
      - "5000:5000"   
    volumes:
      - .:/myapp 
    depends_on:
      - staff_backend    
