version: "3"
services:
  customers_frontend:
    build: "./restaurant_customers" 
    ports:
      - "7272:2000"
    volumes:
      - ./restaurant_customers:/usr/src/app/customers/
    environment:
      - RACK_ENV=docker_development
    depends_on:
      - customers_backend
  customers_backend:
    build: "./restaurant_customers_backend"
    ports:
      - "8888:3000"
    volumes:
      - ./restaurant_customers_backend:/usr/src/app/customers_backend/
    environment:
        - RACK_ENV=docker_development
  staff_frontend:
    build: "./restaurant_staff"
    ports:
      - "9292:4000"   
    volumes:
      - ./restaurant_staff:/usr/src/app/staff/
    environment:
      - RACK_ENV=docker_development
    depends_on:
      - staff_backend
  staff_backend:
    build: "./restaurant_staff_backend"
    ports:
      - "8080:5000" 
    volumes:
      - ./restaurant_staff_backend:/usr/src/app/staff_backend/
    environment:
      - RACK_ENV=docker_development
