development:
  address: http://localhost
  hostname: dev_host
docker_development:
  address: http://192.168.99.100
  hostname: docker_host
test:
  address: http://localhost
  hostname: dev_host
production:
  address: production_host
  hostname: prod_host