# frozen_string_literal: true

source "http://rubygems.org"
gem 'rspec'
gem 'rack', '2.0.5'
gem 'rack-test'
gem 'sinatra'
gem 'json'
gem 'dm-core'
gem 'dm-migrations'
gem 'sequel', '4.48.0'
gem 'sqlite3', '~> 1.3'
gem 'dm-sqlite-adapter', '1.2.0'
gem 'rest-client'
gem 'sinatra-contrib'