# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'rspec'
gem 'rack', '2.0.5'
gem 'rack-test'
gem 'sinatra'
gem 'dm-core'
gem 'dm-migrations'
gem 'dm-sqlite-adapter'
